/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WISECoreJNI */

#ifndef _Included_WISECoreJNI
#define _Included_WISECoreJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WISECoreJNI
 * Method:    core_initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1initialize
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_uninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WISECoreJNI_core_1uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     WISECoreJNI
 * Method:    core_tag_set
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1tag_1set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_product_info_set
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1product_1info_1set
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_account_bind
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1account_1bind
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_callback_set
 * Signature: (LWISECoreJNI;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1callback_1set
  (JNIEnv *, jobject, jobject);

/*
 * Class:     WISECoreJNI
 * Method:    core_action_response
 * Signature: (ILjava/lang/String;ZLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1action_1response
  (JNIEnv *, jobject, jint, jstring, jboolean, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_heartbeatratequery_response
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1heartbeatratequery_1response
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_tls_set
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1tls_1set
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_tls_psk_set
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1tls_1psk_1set
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1connect
  (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_disconnect
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_WISECoreJNI_core_1disconnect
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     WISECoreJNI
 * Method:    core_device_register
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1device_1register
  (JNIEnv *, jobject);

/*
 * Class:     WISECoreJNI
 * Method:    core_heartbeat_send
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1heartbeat_1send
  (JNIEnv *, jobject);

/*
 * Class:     WISECoreJNI
 * Method:    core_publish
 * Signature: (Ljava/lang/String;Ljava/lang/String;JII)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1publish
  (JNIEnv *, jobject, jstring, jstring, jlong, jint, jint);

/*
 * Class:     WISECoreJNI
 * Method:    core_subscribe
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1subscribe
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     WISECoreJNI
 * Method:    core_unsubscribe
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WISECoreJNI_core_1unsubscribe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WISECoreJNI
 * Method:    core_address_get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WISECoreJNI_core_1address_1get
  (JNIEnv *, jobject);

/*
 * Class:     WISECoreJNI
 * Method:    core_error_string_get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WISECoreJNI_core_1error_1string_1get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
